##PROD
services:
  config-service:
    build:
      context: .
    container_name: config-service
    env_file:
      - ../.env
    ports:
      - "8099:8099"
    networks:
      - backend

#QA
  config-service-qa:
    build:
      context: .
    container_name: config-service-qa
    env_file:
      - ../.env
    ports:
      - "8299:8299"
    networks:
      - backend

networks:
  backend:
    external: true