services:
  config-service:
    build:
      context: .
    container_name: config-service
    env_file:
      - ../.env
#    ports:
#      - "8099:8099"
    networks:
      - backend

networks:
  backend:
    external: true