name: Deploy Java Backend via SSH with Password

on:
  push:
    branches:
      - QA

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Dar permissão ao mvnw
        working-directory: config-service
        run: chmod +x mvnw

      - name: Build com Maven
        working-directory: config-service
        run: ./mvnw clean package

      - name: Compactar pasta config-service
        run: tar -cvf config-service.tar config-service/

      - name: Instalar sshpass
        run: sudo apt-get install -y sshpass

      - name: Enviar .tar para VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" scp -o StrictHostKeyChecking=no config-service.tar ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/tmp/config-service.tar

      - name: Executar comandos na VPS
        run: |
          TARGET_DIR="/home/root/QA/Back-End/Config-Server-InEvolving"
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
            set -e
      
            rm -rf "$TARGET_DIR/config-service"
            mkdir -p "$TARGET_DIR"
            tar -xvf /tmp/config-service.tar -C "$TARGET_DIR"
            rm /tmp/config-service.tar

            # Criar arquivo .env diretamente no servidor
            cat > "$TARGET_DIR/.env" << 'ENVFILE'
            GIT_USERNAME=${GIT_USERNAME}
            GIT_TOKEN=${GIT_TOKEN}
            IN_EVOLVING_ENCRYPT_KEY=${IN_EVOLVING_ENCRYPT_KEY}
            ENVFILE
            
            # Permissões
            chmod 600 "$TARGET_DIR/.env"
      
            cd "$TARGET_DIR/config-service"
            docker compose down --volumes --remove-orphans config-service-qa
            docker compose up -d config-service-qa
      
            echo "Containers ativos:"
            docker ps
          EOF
